authentication:
  build: spec/dummy_service
  environment:
    SERVICE_NAME: authentication
inbox:
  build: spec/dummy_service
  environment:
    SERVICE_NAME: inbox

gateway:
  build: app
  links:
    - authentication
    - inbox
  ports:
    - 80

testapp:
  build: spec/app
  links: 
    - gateway
